name: Build and scan image

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to docker registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t larsnieuwenhuizen/dummy-webhook --push .